# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "SERGIO" #example
    #dataset_dir: "example" 

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   exprData: scRNA-Seq expression data file. Cells are along the
    #            columns and genes are along the rows.
    #   cellData: a file containing pseudotime ordering, or any other 
    #             information about cells.
    #   trueEdges: Name of the refrence network file in the
    #              edge list format. Needed for evaluation.
    datasets:
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net0"
          exprData: "simulated_noNoise_bulk_0.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
          
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net1"
          exprData: "simulated_noNoise_bulk_1.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net2"
          exprData: "simulated_noNoise_bulk_2.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net3"
          exprData: "simulated_noNoise_bulk_3.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
          
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net4"
          exprData: "simulated_noNoise_bulk_4.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
          
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net5"
          exprData: "simulated_noNoise_bulk_5.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net6"
          exprData: "simulated_noNoise_bulk_6.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net7"
          exprData: "simulated_noNoise_bulk_7.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net8"
          exprData: "simulated_noNoise_bulk_8.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
          
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net9"
          exprData: "simulated_noNoise_bulk_9.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net10"
          exprData: "simulated_noNoise_bulk_10.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net11"
          exprData: "simulated_noNoise_bulk_11.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
          
        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net12"
          exprData: "simulated_noNoise_bulk_12.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net13"
          exprData: "simulated_noNoise_bulk_13.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"

        - name: "De-noised_100G_9T_300cPerT_4_DS1_bulk/net14"
          exprData: "simulated_noNoise_bulk_14.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"


        


    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:

        - name: "ORDER_MCMC"
          params: 
              should_run: [True]
              # Number of iterations for finding edge weights
              nIter: [50]

        # - name: "PARTITION_MCMC" #This algorithm is very slow for larger datasets (4h for 100x100 matrix of gene expression data)
        #   params: 
        #       should_run: [True]
        #       # Number of iterations for finding edge weights
        #       nIter: [100]

        - name: "PC"
          params: 
              should_run: [True]
              # Number of iterations for finding edge weights
              nIter: [50]

              # If 1, it will return a markov equivalence group represented as pdag, otherwise a dag
              partially_directed: [1]

              # Conditional testing threshold
              alpha: [0.5]

              # Verbosity of pc.fit function
              verbose: [0]


        - name: "GLASSO"
          params: 
              should_run: [True]
              # rho value for preconditioning w, wi
              rho1: [0.001]

              # rho value for final glasso
              rho2: [0.002]



        # - name: "GENIE3"
        #   params: 
        #       should_run: [False]


        - name: "GENIE3_R"
          params: 
              should_run: [True]

              # Number of trees in an ensemble for each target gene. Default: 1000.
              nTrees: [1000]

              # Number of cores to use for parallel computing. Default: 1.
              nCores: [14]

              # Tree-based method used. Must be either "RF" for Random Forests (default) or "ET" for Extra-Trees.
              treeMethod: [RF]

              # Number of candidate regulators randomly selected at each tree node
              K: [sqrt]
              
              
        - name: "GRNBOOST2"
          params: 
              should_run: [True]
              
              
        - name: "PPCOR"
          params: 
              should_run: [True]
              # p-value True
              # Used in parsing output
              pVal: [1]

        - name: "GENENET"
          params: 
              should_run: [True]
              # Number of strongest edges that will be chosen
              num_edges: [0]

              # Directed or undirected
              directed: [1]

              # Verbosity
              verbose: [0]

        - name: "ARACNE"
          params: 
              should_run: [True]
              # Epsilon - see documentation
              eps: [0.2]

        - name: "CORR"
          params: 
              should_run: [True]
              # p-value True
              # Used in parsing output
              pVal: [1]



# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
    output_prefix: "SERGIO_BULK_100"
