# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "SERGIO" #example
    #dataset_dir: "example" 

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   exprData: scRNA-Seq expression data file. Cells are along the
    #            columns and genes are along the rows.
    #   cellData: a file containing pseudotime ordering, or any other 
    #             information about cells.
    #   trueEdges: Name of the refrence network file in the
    #              edge list format. Needed for evaluation.
    datasets:
        - name: "De-noised_1200G_9T_300cPerT_6_DS3/net0"
          exprData: "simulated_noNoise_0.tsv"  
          cellData: "PseudoTime.csv"
          trueEdges: "gt_GRN.tsv"
          
        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net1"
        #   exprData: "simulated_noNoise_1.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net2"
        #   exprData: "simulated_noNoise_2.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net3"
        #   exprData: "simulated_noNoise_3.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"
          
        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net4"
        #   exprData: "simulated_noNoise_4.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"
          
        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net5"
        #   exprData: "simulated_noNoise_5.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net6"
        #   exprData: "simulated_noNoise_6.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net7"
        #   exprData: "simulated_noNoise_7.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"
        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net8"
        #   exprData: "simulated_noNoise_8.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"
          
        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net9"
        #   exprData: "simulated_noNoise_9.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net10"
        #   exprData: "simulated_noNoise_10.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net11"
        #   exprData: "simulated_noNoise_11.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"
          
        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net12"
        #   exprData: "simulated_noNoise_12.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net13"
        #   exprData: "simulated_noNoise_13.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"

        # - name: "De-noised_1200G_9T_300cPerT_6_DS3/net14"
        #   exprData: "simulated_noNoise_14.tsv"  
        #   cellData: "PseudoTime.csv"
        #   trueEdges: "gt_GRN.tsv"


        


    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:

        - name: "ORDER_MCMC"
          params: 
              should_run: [False]
              # Number of iterations for finding edge weights
              nIter: [9]

              # Percentage of data for each iteration
              sample_size: [0.7]


        - name: "PARTITION_MCMC" #This algorithm is very slow for larger datasets (4h for 100x100 matrix of gene expression data)
          params: 
              should_run: [False]
              # Number of iterations for finding edge weights
              nIter: [3]

              # Percentage of data for each iteration
              sample_size: [0.7]


        - name: "PC"
          params: 
              should_run: [False]
              # Number of iterations for finding edge weights
              nIter: [500]

              # If 1, it will return a markov equivalence group represented as pdag, otherwise a dag
              partially_directed: [0]

              # Conditional testing threshold
              alpha: [0.01]

              # Verbosity of pc.fit function
              verbose: [0]

              # Percentage of data for each iteration
              sample_size: [0.7]


        - name: "GLASSO"
          params: 
              should_run: [True]
              # rho value for preconditioning w, wi
              rho1: [0.001]

              # rho value for final glasso
              rho2: [0.002]

              # nIter for bootstrapping
              nIter: [20]

              # sample_size (in percent) for bootstrapping
              sample_size: [0.7]


        - name: "GENIE3"
          params: 
              should_run: [False]
              
              
        - name: "GRNBOOST2"
          params: 
              should_run: [False]
              
              
        - name: "PPCOR"
          params: 
              should_run: [True]
              # p-value True
              # Used in parsing output
              pVal: [4.88440092439776e-07]

        - name: "GENENET"
          params: 
              should_run: [True]
              # Number of strongest edges that will be chosen
              num_edges: [300]

              # Directed or undirected
              directed: [0]

              # Verbosity
              verbose: [0]

        - name: "ARACNE"
          params: 
              should_run: [True]
              # Epsilon - see documentation
              eps: [0]
            
      # - name: "PIDC"
      #   params: 
      #       should_run: [False]


# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
    output_prefix: "SERGIO"
